language: php

php:
  - 5.5
  - 5.4
  - hhvm

before_script:
	- composer self-update || true
	- composer install --dev

after_script:
  - php vendor/bin/coveralls -v

matrix:
	allow_failures:
		- php: hhvm
